### ISSUE TITLE
n3iwf

### ISSUE THREAD

**Issue by LHXQL** [free5gc/n3iwf#18]
~/free5gc$ make
Start building n3iwf....
cd NFs/n3iwf/cmd && \
CGO_ENABLED=0 go build -gcflags "" -ldflags "-X github.com/free5gc/util/version.VERSION=v3.2.1 -X github.com/free5gc/util/version.BUILD_TIME=2023-03-27T06:47:54Z -X github.com/free5gc/util/version.C         COMMIT_HASH=+e777e4e -X github.com/free5gc/util/version.COMMIT_TIME=2023-03-06T13:35:40Z" -o /home/u         ubuntu/free5gc/bin/n3iwf main.go
go: downloading github.com/gin-gonic/gin v1.7.3
go: downloading github.com/wmnsk/go-gtp v0.8.0
verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        go.sum:     h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [Makefile:46: bin/n3iwf] Error 1

**Comment by andy89923** [comment]
In your scenario, I think the following commands would help you.
```shell
$ cd NFs/n3iwf
```

In ```free5gc/NFs/n3iwf```
```shell
$ go clean -modcache
$ go mod tidy
```

Go back to ```free5gc/``
```shell
$ make
```
