### ISSUE TITLE
Problem in Go get 

### ISSUE THREAD

**Issue by Jaditya-89** [free5gc/n3iwf#24]
Hi, 

I am trying to use this library for implementation IKEv2 on local machine. However, when I do
```
go get github.com/free5gc/n3iwf@latest
```
I am getting a library with tag 1.3.0 but It does not resemble to the latest code which is getting reflected in this Github Repo. Can you please tell which tag should I use to get the latest version of this library.

**Comment by Jaditya-89** [comment]
@brianchennn please help in answering my query

**Comment by brianchennn** [comment]
@Jaditya-89 
You should use **22988ee** because it matches the newest version of [free5gc](https://github.com/free5gc/free5gc) (v3.3.0), and we did a lot of internal tests on that commit.

**Comment by Jaditya-89** [comment]
Hi @brianchennn , thank you for answering my question. So, I should use tag v1.2.0 for having latest changes for this ike library ?
